# Generated by Django 5.1.1 on 2025-02-09 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('temperatura', models.FloatField()),
                ('turbidez', models.FloatField()),
                ('tds', models.FloatField()),
                ('co2', models.FloatField()),
                ('ejecucion', models.IntegerField()),
            ],
        ),
    ]
