# Generated by Django 5.1.1 on 2025-02-09 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('temperatura', models.FloatField()),
                ('turbidez', models.FloatField()),
                ('tds', models.FloatField()),
                ('co2', models.FloatField()),
                ('ejecucion', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Medida',
        ),
    ]
