# Generated by Django 5.1.1 on 2025-02-09 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_datos_delete_medida'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Datos',
            new_name='Dato',
        ),
    ]
