# Generated by Django 5.1.1 on 2025-02-10 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_rename_datos_dato'),
    ]

    operations = [
        migrations.AddField(
            model_name='dato',
            name='ph',
            field=models.FloatField(default=5),
            preserve_default=False,
        ),
    ]
